service: serverless-nest-microservice-template
frameworkVersion: '3'

plugins:
  - serverless-offline
  # - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello-world:
    handler: dist/template/handler.helloWorld
    # handler: dist/main.handler
    events:
      - http:
          path: test
          method: get
          cors: true
  bye-world:
    handler: dist/template/handler.byeWorld
    events:
      - http:
          path: test2
          method: get
          cors: true

