service: serverless-nest-microservice-template
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true # to package functions individually. You can toggle this and check the difference webpack generates

custom:
  webpack: # serverless-webpack plugin options
    webpackConfig: webpack.config.js # Name of webpack configuration file
    includeModules: true
    packager: 'npm' # Packager that will be used to package your external modules

provider:
  name: aws
  runtime: nodejs18.x

functions:
  helloWorld:
    handler: src/main.handler
    name: helloWorld #THE RIGHT NAME HERE IS VERY IMPORTANT
    events:
      - httpApi:
          path: /template
          method: GET
