service: serverless-nest-microservice-template
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true # to package functions individually. You can toggle this and check the difference webpack generates

custom:
  webpack: # serverless-webpack plugin options
    webpackConfig: webpack.config.js # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello-world:
    handler: src/main.helloWorld
    events:
      - http:
          path: test
          method: get
          cors: true
